import type { Facility, UnitType, StorageUnit, RentedContract, SupportTicket } from './types';

/**
 * Danh sách cơ sở lưu trữ tại TP.HCM (Khớp SCR-SC-01)
 */
export const mockFacilities: Facility[] = [
  {
    id: 'FAC-D7-01',
    code: 'D7-FLAGSHIP',
    name: 'SmartStorage Quận 7 Flagship',
    address: '52 Nguyễn Hữu Thọ, Phường Tân Phong, Quận 7',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    distance: '1.8 km',
    startingPrice: 650000,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    phone: '1900 8888',
  },
  {
    id: 'FAC-D7-02',
    code: 'D7-PMH',
    name: 'SmartStorage Phú Mỹ Hưng',
    address: '45 Nguyễn Văn Linh, Phường Tân Phong, Quận 7',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    distance: '2.6 km',
    startingPrice: 750000,
    image: 'https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=800&q=80',
    phone: '1900 8888',
  },
  {
    id: 'FAC-D7-03',
    code: 'D7-HIMLAM',
    name: 'SmartStorage Him Lam Center',
    address: '88 Đường Số 1, KDC Him Lam, Phường Tân Hưng, Quận 7',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    distance: '1.2 km',
    startingPrice: 650000,
    image: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=800&q=80',
    phone: '1900 8888',
  },
];

/**
 * Danh mục 4 loại kích thước kho (Khớp chính xác SCR-SC-01B)
 */
export const mockUnitTypes: UnitType[] = [
  {
    id: 'UT-S-STD',
    code: 'TYPE-S',
    name: 'Kho Cỡ S – Tủ Đồ Cá Nhân',
    sizeCategory: 'S',
    storageType: 'STANDARD',
    areaM2: 1.5,
    volumeM3: 3.0,
    dimensions: '1.0m x 1.5m x 2.0m',
    capacityDescription: 'Chứa vừa 6–10 thùng carton hoặc vali + đồ dùng cá nhân',
    baseMonthlyPrice: 1200000,
    badge: 'COMPACT',
  },
  {
    id: 'UT-M-STD',
    code: 'TYPE-M',
    name: 'Kho Cỡ M – Tiêu Chuẩn Gia Đình',
    sizeCategory: 'M',
    storageType: 'STANDARD',
    areaM2: 3.0,
    volumeM3: 7.5,
    dimensions: '1.5m x 2.0m x 2.5m',
    capacityDescription: 'Chứa vừa 15–20 thùng carton hoặc 1 xe máy + đồ đạc gia đình',
    baseMonthlyPrice: 2400000,
    badge: 'POPULAR',
  },
  {
    id: 'UT-L-STD',
    code: 'TYPE-L',
    name: 'Kho Cỡ L – Không Gian Rộng',
    sizeCategory: 'L',
    storageType: 'STANDARD',
    areaM2: 6.0,
    volumeM3: 15.0,
    dimensions: '2.0m x 3.0m x 2.5m',
    capacityDescription: 'Chứa vừa 30+ thùng carton hoặc toàn bộ nội thất căn hộ 2 phòng ngủ',
    baseMonthlyPrice: 4500000,
    badge: 'SPACIOUS',
  },
  {
    id: 'UT-XL-STD',
    code: 'TYPE-XL',
    name: 'Kho Cỡ XL – Doanh Nghiệp',
    sizeCategory: 'XL',
    storageType: 'STANDARD',
    areaM2: 12.0,
    volumeM3: 30.0,
    dimensions: '3.0m x 4.0m x 2.5m',
    capacityDescription: 'Chứa vừa 50+ thùng carton hoặc pallet hàng hóa kinh doanh lớn',
    baseMonthlyPrice: 8000000,
    badge: 'COMMERCIAL',
  },
  // Chế độ máy lạnh (Climate-Controlled Storage - 22°C-25°C)
  {
    id: 'UT-S-AC',
    code: 'TYPE-S-AC',
    name: 'Kho Cỡ S – Tủ Đồ Cá Nhân (Máy Lạnh)',
    sizeCategory: 'S',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 1.5,
    volumeM3: 3.0,
    dimensions: '1.0m x 1.5m x 2.0m',
    capacityDescription: 'Kiểm soát nhiệt độ 22°C–25°C, chống ẩm mốc cho tài liệu & quần áo cao cấp',
    baseMonthlyPrice: 1500000,
    badge: 'COMPACT',
  },
  {
    id: 'UT-M-AC',
    code: 'TYPE-M-AC',
    name: 'Kho Cỡ M – Tiêu Chuẩn Gia Đình (Máy Lạnh)',
    sizeCategory: 'M',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 3.0,
    volumeM3: 7.5,
    dimensions: '1.5m x 2.0m x 2.5m',
    capacityDescription: 'Kho mát 24/7, lý tưởng cho đồ gỗ mỹ nghệ, thiết bị điện tử gia dụng',
    baseMonthlyPrice: 2800000,
    badge: 'POPULAR',
  },
  {
    id: 'UT-L-AC',
    code: 'TYPE-L-AC',
    name: 'Kho Cỡ L – Không Gian Rộng (Máy Lạnh)',
    sizeCategory: 'L',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 6.0,
    volumeM3: 15.0,
    dimensions: '2.0m x 3.0m x 2.5m',
    capacityDescription: 'Nhiệt độ ổn định, phù hợp lưu trữ hàng hóa cao cấp hoặc thiết bị studio',
    baseMonthlyPrice: 5200000,
    badge: 'SPACIOUS',
  },
  {
    id: 'UT-XL-AC',
    code: 'TYPE-XL-AC',
    name: 'Kho Cỡ XL – Doanh Nghiệp (Máy Lạnh)',
    sizeCategory: 'XL',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 12.0,
    volumeM3: 30.0,
    dimensions: '3.0m x 4.0m x 2.5m',
    capacityDescription: 'Kho mát diện tích lớn phục vụ lưu trữ kho vận, thương mại điện tử chuyên nghiệp',
    baseMonthlyPrice: 9200000,
    badge: 'COMMERCIAL',
  },
];

/**
 * Danh sách ô kho mẫu trên sơ đồ mặt bằng Tầng 1 & Tầng 2
 * Đủ 6 trạng thái để kiểm thử sơ đồ Interactive Unit Picker (SC-02, BR-AVL-01)
 */
export const mockStorageUnits: StorageUnit[] = [
  // ==================== CƠ SỞ PHÚ MỸ HƯNG (FAC-D7-02) - TẦNG 1 ====================
  // Dãy Zone A (Loại S & M)
  {
    id: 'U-A101',
    unitNumber: 'A101',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-S-STD',
    floor: 1,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'S',
    storageType: 'STANDARD',
    areaM2: 1.5,
    monthlyPrice: 1200000,
  },
  {
    id: 'U-A102',
    unitNumber: 'A102',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-S-STD',
    floor: 1,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'S',
    storageType: 'STANDARD',
    areaM2: 1.5,
    monthlyPrice: 1200000,
  },
  {
    id: 'U-A103',
    unitNumber: 'A103',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-S-STD',
    floor: 1,
    zone: 'Zone A',
    status: 'OCCUPIED',
    sizeCategory: 'S',
    storageType: 'STANDARD',
    areaM2: 1.5,
    monthlyPrice: 1200000,
  },
  {
    id: 'U-A104',
    unitNumber: 'A104',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-S-STD',
    floor: 1,
    zone: 'Zone A',
    status: 'RESERVED',
    sizeCategory: 'S',
    storageType: 'STANDARD',
    areaM2: 1.5,
    monthlyPrice: 1200000,
  },
  {
    id: 'U-A105',
    unitNumber: 'A105',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-S-AC',
    floor: 1,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'S',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 1.5,
    monthlyPrice: 1500000,
  },
  {
    id: 'U-A106',
    unitNumber: 'A106',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-S-AC',
    floor: 1,
    zone: 'Zone A',
    status: 'MAINTENANCE',
    sizeCategory: 'S',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 1.5,
    monthlyPrice: 1500000,
  },
  {
    id: 'U-A107',
    unitNumber: 'A107',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-M-STD',
    floor: 1,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'M',
    storageType: 'STANDARD',
    areaM2: 3.0,
    monthlyPrice: 2400000,
  },
  {
    id: 'U-A108',
    unitNumber: 'A108',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-M-STD',
    floor: 1,
    zone: 'Zone A',
    status: 'OCCUPIED',
    sizeCategory: 'M',
    storageType: 'STANDARD',
    areaM2: 3.0,
    monthlyPrice: 2400000,
  },
  {
    id: 'U-A109',
    unitNumber: 'A109',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-M-STD',
    floor: 1,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'M',
    storageType: 'STANDARD',
    areaM2: 3.0,
    monthlyPrice: 2400000,
  },
  {
    id: 'U-A110',
    unitNumber: 'A110',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-M-AC',
    floor: 1,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'M',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 3.0,
    monthlyPrice: 2800000,
  },

  // Dãy Zone B (Loại L & XL)
  {
    id: 'U-B201',
    unitNumber: 'B201',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-L-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'L',
    storageType: 'STANDARD',
    areaM2: 6.0,
    monthlyPrice: 4500000,
  },
  {
    id: 'U-B202',
    unitNumber: 'B202',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-L-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'OCCUPIED',
    sizeCategory: 'L',
    storageType: 'STANDARD',
    areaM2: 6.0,
    monthlyPrice: 4500000,
  },
  {
    id: 'U-B203',
    unitNumber: 'B203',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-L-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'RESERVED',
    sizeCategory: 'L',
    storageType: 'STANDARD',
    areaM2: 6.0,
    monthlyPrice: 4500000,
  },
  {
    id: 'U-B204',
    unitNumber: 'B204',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-L-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'L',
    storageType: 'STANDARD',
    areaM2: 6.0,
    monthlyPrice: 4500000,
  },
  {
    id: 'U-B205',
    unitNumber: 'B205',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-XL-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'XL',
    storageType: 'STANDARD',
    areaM2: 12.0,
    monthlyPrice: 8000000,
  },
  {
    id: 'U-B206',
    unitNumber: 'B206',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-XL-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'OCCUPIED',
    sizeCategory: 'XL',
    storageType: 'STANDARD',
    areaM2: 12.0,
    monthlyPrice: 8000000,
  },
  {
    id: 'U-B207',
    unitNumber: 'B207',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-XL-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'XL',
    storageType: 'STANDARD',
    areaM2: 12.0,
    monthlyPrice: 8000000,
  },
  {
    id: 'U-B208',
    unitNumber: 'B208',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-XL-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'OVERDUE',
    sizeCategory: 'XL',
    storageType: 'STANDARD',
    areaM2: 12.0,
    monthlyPrice: 8000000,
  },
  {
    id: 'U-B209',
    unitNumber: 'B209',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-XL-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'LOCKED',
    sizeCategory: 'XL',
    storageType: 'STANDARD',
    areaM2: 12.0,
    monthlyPrice: 8000000,
  },
  {
    id: 'U-B210',
    unitNumber: 'B210',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-XL-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'XL',
    storageType: 'STANDARD',
    areaM2: 12.0,
    monthlyPrice: 8000000,
  },

  // ==================== CƠ SỞ PHÚ MỸ HƯNG (FAC-D7-02) - TẦNG 2 ====================
  {
    id: 'U-A201',
    unitNumber: 'A201',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-S-STD',
    floor: 2,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'S',
    storageType: 'STANDARD',
    areaM2: 1.5,
    monthlyPrice: 1200000,
  },
  {
    id: 'U-A202',
    unitNumber: 'A202',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-M-STD',
    floor: 2,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'M',
    storageType: 'STANDARD',
    areaM2: 3.0,
    monthlyPrice: 2400000,
  },
  {
    id: 'U-A203',
    unitNumber: 'A203',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-M-AC',
    floor: 2,
    zone: 'Zone A',
    status: 'RESERVED',
    sizeCategory: 'M',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 3.0,
    monthlyPrice: 2800000,
  },
  {
    id: 'U-B301',
    unitNumber: 'B301',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-L-STD',
    floor: 2,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'L',
    storageType: 'STANDARD',
    areaM2: 6.0,
    monthlyPrice: 4500000,
  },
  {
    id: 'U-B302',
    unitNumber: 'B302',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-L-AC',
    floor: 2,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'L',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 6.0,
    monthlyPrice: 5200000,
  },
  {
    id: 'U-B303',
    unitNumber: 'B303',
    facilityId: 'FAC-D7-02',
    unitTypeId: 'UT-XL-AC',
    floor: 2,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'XL',
    storageType: 'CLIMATE_CONTROLLED',
    areaM2: 12.0,
    monthlyPrice: 9200000,
  },

  // ==================== CƠ SỞ QUẬN 7 FLAGSHIP (FAC-D7-01) - TẦNG 1 ====================
  {
    id: 'U-F101',
    unitNumber: 'F101',
    facilityId: 'FAC-D7-01',
    unitTypeId: 'UT-S-STD',
    floor: 1,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'S',
    storageType: 'STANDARD',
    areaM2: 1.5,
    monthlyPrice: 1200000,
  },
  {
    id: 'U-F102',
    unitNumber: 'F102',
    facilityId: 'FAC-D7-01',
    unitTypeId: 'UT-M-STD',
    floor: 1,
    zone: 'Zone A',
    status: 'AVAILABLE',
    sizeCategory: 'M',
    storageType: 'STANDARD',
    areaM2: 3.0,
    monthlyPrice: 2400000,
  },
  {
    id: 'U-F103',
    unitNumber: 'F103',
    facilityId: 'FAC-D7-01',
    unitTypeId: 'UT-L-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'L',
    storageType: 'STANDARD',
    areaM2: 6.0,
    monthlyPrice: 4500000,
  },
  {
    id: 'U-F104',
    unitNumber: 'F104',
    facilityId: 'FAC-D7-01',
    unitTypeId: 'UT-XL-STD',
    floor: 1,
    zone: 'Zone B',
    status: 'AVAILABLE',
    sizeCategory: 'XL',
    storageType: 'STANDARD',
    areaM2: 12.0,
    monthlyPrice: 8000000,
  },
];

/**
 * 2 Hợp đồng mẫu cho khách hàng Xuân Nhi (Khớp SCR-SC-04 My Rentals)
 */
export const mockRentedContracts: RentedContract[] = [
  {
    id: 'CTR-2026-089',
    contractNumber: 'HD-SS-2026089',
    facilityId: 'FAC-D7-02',
    facilityName: 'SmartStorage Phú Mỹ Hưng',
    unitId: 'U-A108',
    unitNumber: 'A108',
    unitTypeName: 'Kho Cỡ M – Tiêu Chuẩn Gia Đình',
    sizeCategory: 'M',
    storageType: 'STANDARD',
    startDate: '2026-08-01',
    endDate: '2026-11-01',
    monthlyRent: 2400000,
    depositHeld: 2400000,
    accessPin: '8392', // Đã nghiệm thu quầy -> Cấp mã PIN (BR-ACC-01)
    status: 'ACTIVE',
  },
  {
    id: 'CTR-2026-104',
    contractNumber: 'HD-SS-2026104',
    facilityId: 'FAC-D7-01',
    facilityName: 'SmartStorage Quận 7 Flagship',
    unitId: 'U-A104',
    unitNumber: 'A104',
    unitTypeName: 'Kho Cỡ S – Tủ Đồ Cá Nhân',
    sizeCategory: 'S',
    storageType: 'STANDARD',
    startDate: '2026-09-25',
    endDate: '2026-12-25',
    monthlyRent: 1200000,
    depositHeld: 1200000,
    accessPin: undefined, // Pending Check-in: Chưa cấp mã PIN trước khi đối chiếu CCCD tại quầy (BR-ACC-01, BR-CHK-01)
    status: 'PENDING_CHECKIN',
  },
];

/**
 * Danh sách vé yêu cầu hỗ trợ mẫu (SC-06, SCR-SC-06, BR-SUP-01..03)
 */
export const mockSupportTickets: SupportTicket[] = [
  {
    id: 1,
    ticketCode: 'TKT-20260920-0012',
    customerId: 1,
    customerName: 'Xuân Nhi',
    customerPhone: '0988 776 655',
    contractId: 89,
    contractNumber: 'HD-SS-2026089',
    facilityId: 2,
    facilityName: 'SmartStorage Phú Mỹ Hưng',
    storageUnitId: 8,
    unitNumber: 'A108',
    category: 'LOCK_ACCESS',
    isUrgent: true,
    slaHours: 2, // BR-SUP-01: SLA khẩn cấp kẹt khóa 2 giờ
    description: 'Ổ khóa điện tử báo đèn đỏ liên tục không mở được dù nhập đúng mã PIN 8392. Tôi đang cần lấy giấy tờ gấp để đi công tác.',
    status: 'RESOLVED',
    assignedStaffId: 2,
    assignedStaffName: 'Trần Văn Hoàng (Staff Desk)',
    assignedStaffPhone: '0908 123 456',
    resolutionNote: 'Đã thay bộ pin phụ cho ổ khóa điện tử và vệ sinh chốt cơ. Đã kiểm tra mở thử nghiệm thành công 3 lần với mã PIN của khách hàng.',
    resolvedAt: '2026-09-20T16:30:00Z',
    autoCloseDeadline: '2026-09-27T16:30:00Z', // BR-SUP-03: Tự đóng sau 7 ngày làm việc
    createdAt: '2026-09-20T14:45:00Z',
    updatedAt: '2026-09-20T16:30:00Z',
    attachments: [
      {
        id: 101,
        fileUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
        fileType: 'image/jpeg',
        uploadedAt: '2026-09-20T14:45:00Z',
      },
    ],
    resolutionAttachments: [
      {
        id: 102,
        fileUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
        fileType: 'image/jpeg',
        uploadedAt: '2026-09-20T16:25:00Z',
      },
    ],
  },
  {
    id: 2,
    ticketCode: 'TKT-20260921-0034',
    customerId: 1,
    customerName: 'Xuân Nhi',
    customerPhone: '0988 776 655',
    contractId: 89,
    contractNumber: 'HD-SS-2026089',
    facilityId: 2,
    facilityName: 'SmartStorage Phú Mỹ Hưng',
    storageUnitId: 8,
    unitNumber: 'A108',
    category: 'UNIT_DAMAGE',
    isUrgent: false,
    slaHours: 24,
    description: 'Bóng đèn trần hành lang trước cửa kho A108 bị chập chờn, thỉnh thoảng tắt tối om gây bất tiện khi bốc dỡ hàng buổi tối.',
    status: 'IN_PROGRESS',
    assignedStaffId: 3,
    assignedStaffName: 'Lê Văn Hùng (Kỹ thuật viên cơ sở)',
    assignedStaffPhone: '0912 345 678',
    createdAt: '2026-09-21T09:15:00Z',
    updatedAt: '2026-09-21T10:00:00Z',
    attachments: [
      {
        id: 103,
        fileUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
        fileType: 'image/jpeg',
        uploadedAt: '2026-09-21T09:15:00Z',
      },
    ],
    resolutionAttachments: [],
  },
  {
    id: 3,
    ticketCode: 'TKT-20260921-0045',
    customerId: 1,
    customerName: 'Xuân Nhi',
    customerPhone: '0988 776 655',
    contractId: 104,
    contractNumber: 'HD-SS-2026104',
    facilityId: 1,
    facilityName: 'SmartStorage Quận 7 Flagship',
    category: 'PAYMENT',
    isUrgent: false,
    slaHours: 48,
    description: 'Tôi đã thực hiện quét mã VietQR thanh toán tiền cọc cho hợp đồng HD-SS-2026104 lúc 10h15 sáng nay nhưng hệ thống chưa tự động cập nhật biên lai điện tử.',
    status: 'NEW',
    createdAt: '2026-09-21T11:00:00Z',
    updatedAt: '2026-09-21T11:00:00Z',
    attachments: [],
    resolutionAttachments: [],
  },
  {
    id: 4,
    ticketCode: 'TKT-20260910-0008',
    customerId: 1,
    customerName: 'Xuân Nhi',
    customerPhone: '0988 776 655',
    contractId: 89,
    contractNumber: 'HD-SS-2026089',
    facilityId: 2,
    facilityName: 'SmartStorage Phú Mỹ Hưng',
    storageUnitId: 8,
    unitNumber: 'A108',
    category: 'BELONGINGS',
    isUrgent: false,
    slaHours: 24,
    description: 'Cần đăng ký mượn xe nâng tay và xe đẩy tải trọng 300kg tại sảnh bốc dỡ vào sáng Thứ Bảy tuần tới.',
    status: 'CLOSED',
    assignedStaffId: 2,
    assignedStaffName: 'Trần Văn Hoàng (Staff Desk)',
    resolutionNote: 'Đã bố trí sẵn xe đẩy số 03 tại quầy lễ tân tầng trệt và hướng dẫn khách nhận thiết bị thuận lợi.',
    resolvedAt: '2026-09-10T14:00:00Z',
    createdAt: '2026-09-10T08:30:00Z',
    updatedAt: '2026-09-10T14:30:00Z',
    attachments: [],
    resolutionAttachments: [],
  },
];

/**
 * Câu hỏi thường gặp dành cho khách hàng (Khớp Wireframe SCR-SC-06 & Business Rules)
 */
export interface SupportFaq {
  id: number;
  question: string;
  answer: string;
  category: string;
}

export const mockSupportFaqs: SupportFaq[] = [
  {
    id: 1,
    question: 'Khi nào tôi được hoàn tiền đặt cọc sau khi trả kho?',
    answer: 'Tiền cọc sẽ được hoàn trả tự động vào tài khoản ngân hàng của bạn trong vòng tối đa 07 ngày làm việc sau khi hai bên ký biên bản nghiệm thu trả kho không phát sinh hư hại.',
    category: 'Hoàn tiền & Đặt cọc',
  },
  {
    id: 2,
    question: 'Nếu tôi bị kẹt khóa hoặc quên mã PIN thì xử lý mất bao lâu?',
    answer: 'Theo tiêu chuẩn dịch vụ khẩn cấp, các sự cố về kẹt khóa cơ, hỏng khóa số, quên mã PIN hoặc mất thẻ từ sẽ được nhân viên trực quầy xử lý tận nơi trong vòng tối đa 02 giờ.',
    category: 'Khóa & Truy cập',
  },
  {
    id: 3,
    question: 'Chi phí sửa chữa hư hại trong ô kho được tính như thế nào?',
    answer: 'Đối với sự cố do hạ tầng cơ sở (thấm dột, hệ thống điện), cơ sở chịu 100% chi phí khắc phục. Nếu sự cố do tác động chủ quan từ khách hàng, chi phí sửa chữa sẽ căn cứ theo biên bản kiểm tra và thỏa thuận thực tế.',
    category: 'Chi phí & Bồi thường',
  },
  {
    id: 4,
    question: 'Quy trình nghiệm thu sau khi nhân viên xử lý xong sự cố?',
    answer: 'Nhân viên bắt buộc cập nhật ghi chú và ảnh hiện trường sau khi xử lý. Bạn có thể bấm "Xác nhận hài lòng" để đóng ticket. Nếu sau 07 ngày làm việc bạn không phản hồi, hệ thống sẽ tự động đóng ticket.',
    category: 'Nghiệm thu & Đóng vé',
  },
];

